### ISSUE TITLE
Does this plugin plan to support iOS?

### ISSUE THREAD

**Issue by sinacn546** [jaydangar/chaquopy_flutter#1]

**Comment by jaydangar** [comment]
@sinacn546 , since chaquopy only supports android, there's no way I can communicate with iOS. The only way to integrate python in iOS is finding an alternative of chaquopy on iOS platform, which is right now not available. I am open to suggestions and if you want to help, kindly email me your ideas or write it down here.

**Comment by jaydangar** [comment]
Since this plugin uses chaquopy library internally and chaquopy only supports android, we can't use it on iOS platform. If in future chaquopy adds iOS or other platform support, we can modify this plugin to support more platforms for sure.

**Comment by Marco410** [comment]
do you know any Chaquopy alternative to run python scripts on iOS?

**Comment by jaydangar** [comment]
startflut is the plugin which provides this functionality.

**Comment by dhaval-k-simformsolutions** [comment]
> startflut is the plugin which provides this functionality.

This plugin in inactive from last 14 months.
