### ISSUE TITLE
Can We Run any Python Library except the ones that open up platform specific stuff?

### ISSUE THREAD

**Issue by TejasDhanda-L11** [jaydangar/chaquopy_flutter#9]
Instances of platform specific stuff:
1. Tkinter
2. Opening Web-browser for dynamic scraping (that I would really love to do if possible)
etc

**Comment by jaydangar** [comment]
for webscrapping on flutter can be done via [this](https://pub.dev/packages/web_scraper) package, you can easily open webview and webscrape it via the package defined above. the problem with chaquopy is that it doesn't easily deal with android GUI part, that's why it does not support OpenCV, Matplotlib as of now.

**Comment by jaydangar** [comment]
If you really like to see the real problem with chaquopy and android GUI, checkout this [app](https://play.google.com/store/apps/details?id=com.dcodeai.dcodeai_playground). This app does have support for OpenCV, Matplotlib, but you need to make the configurations as well as since you are using chaquopy, your exact error won't show up.
